#ifndef DEVICE_CONFIG_H
#define DEVICE_CONFIG_H

#define DEVICE_ID "IOT-ENV-001"
#define DEVICE_NAME "Environment Sensor Node"
#define FIRMWARE_VERSION "1.0.0"

#define SERIAL_BAUD_RATE 115200
#define SENSOR_READ_INTERVAL_MS 2000

#define TELEMETRY_MAX_ATTEMPTS 3
#define TELEMETRY_RETRY_DELAY_MS 1000

#endif
